language: php
php:
  # - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=stable
    - RELEASE=dev
    allow_failures:
      - hhvm: RELEASE=stable
      - hhvm: RELEASE=dev

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

script:
  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core:8.1.x-dev; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  - ./../vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
  - ./../vendor/bin/drush status
  # Skip Drupal Console ("drupal") testing as it's not supported with 8.1.x yet.
  # - ./../vendor/bin/drupal init --override --verbose --uri http://127.0.0.1:8080 --no-interaction
  # - ./../vendor/bin/drupal list
  # - ./../vendor/bin/drupal self-update
