language: php
php:
  # - 5.6
  - 7.0
  - nightly
  # - hhvm

sudo: false

addons:
  - mariadb: '10.1'

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SIMPLETEST_DB=mysql://root:@127.0.0.1:3306/drupal
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=stable
    - RELEASE=dev

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  # - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then sudo echo 'sendmail_path = /bin/true' >> /etc/hhvm/server.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

before_script:
  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core:8.1.x-dev; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  - openssl rand -hex 16 > admin_pw.txt

script:
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=mysql://root:@127.0.0.1:3306/drupal --account-pass=$(cat $TRAVIS_BUILD_DIR/admin_pw.txt)
  - ./../vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
  - ./../vendor/bin/drush status
  # Skip Drupal Console ("drupal") testing as it's not supported with 8.1.x yet.
  # - ./../vendor/bin/drupal init --override --verbose --uri http://127.0.0.1:8080 --no-interaction
  # - ./../vendor/bin/drupal list
  # - ./../vendor/bin/drupal self-update
