language: php
php:
  # - 5.6
  - 7.0
  # - nightly
  - hhvm

sudo: required

addons:
  mariadb: '10.1'

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SIMPLETEST_DB=mysql://root:@127.0.0.1:3306/drupal
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=stable
    # - RELEASE=dev

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
  - sudo update-ca-certificates --fresh
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

before_script:
  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core:8.1.x-dev; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  - openssl rand -hex 16 > admin_pw.txt

script:
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=mysql://root:@127.0.0.1:3306/drupal --account-pass=$(cat $TRAVIS_BUILD_DIR/admin_pw.txt) standard install_configure_form.update_status_module='array(FALSE,FALSE)'
  - ./../vendor/bin/drush runserver http://127.0.0.1:8080 &
  # - phantomjs --webdriver=4444 &
  - sleep 3
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  # - ./../vendor/bin/phpunit -c core --exclude-group Composer
  # Skipping Database tests to see if other tests pass on HHVM
  # - ./../vendor/bin/phpunit -c core --exclude-group Composer,Database,dblog --log-tap build-log-tap-$(date +"%Y-%m-%d")-$TRAVIS_JOB_NUMBER.txt
  # - curl -F "file=@build-log-tap-$(date +"%Y-%m-%d")-$TRAVIS_JOB_NUMBER.txt" https://file.io/?expires=3
  # Quick front page screenshot test
  - phantomjs ../tests/phantomjs/front_page.js
  - mv front_page.png front_page-$(date +"%Y-%m-%d")-$TRAVIS_JOB_NUMBER.png
  - curl -F "file=@front_page-$(date +"%Y-%m-%d")-$TRAVIS_JOB_NUMBER.png" --insecure https://file.io/?expires=3
  - ./../vendor/bin/drush status
  # Skip Drupal Console ("drupal") testing as it's not supported with 8.1.x yet.
  # - ./../vendor/bin/drupal init --override --verbose --uri http://127.0.0.1:8080 --no-interaction
  # - ./../vendor/bin/drupal list
  # - ./../vendor/bin/drupal self-update
