<?php

/**
 * @file
 * Contains organisation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function organisation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the organisation module.
    case 'help.page.organisation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Generates and maintains the various organisational taxonomies and information for the Intranet.') . '</p>';
      return $output;

    default:
  }
}
